### ISSUE TITLE
RM-Bridge-Server 無法找到設備

### ISSUE THREAD

**Issue by ji3g4m6zo6** [FuYaoDe/dockers#1]
您好 謝謝您提供 `RM-Bridge-Server image `
執行後發現 Server 有啟動
但無法透過`RM Bridge - Management Console(Web)`搜尋到 RM2 設備
是因為 APK 版本太低嗎？（透過原生安卓 App 能搜尋到）
謝謝

**Comment by FuYaoDe** [comment]
哈摟 @ji3g4m6zo6
你可以試試看改 Dockerfile 重編譯一個 image 試試看喔
把 apk 替換掉然後 Dockerfile 改檔名就 OK 了
這個 image 我也很久沒有 maintain
當初也只是個 Side project，我忘記最後有沒有成功
只記得最後我們找了個沒用的手機當 Server 解決了

**Comment by ji3g4m6zo6** [comment]
嘗試換過版本後，還是無法搜尋到設備。 
謝謝：）
